### ISSUE TITLE
Petit retour rapide

### ISSUE THREAD

**Issue by LudovicRougier** [Arnocaster/BATTLE-RPG-EN-PROMPT#1]
Le jeu est très sympa, le fait de garder les tours précédents est sympathique. 
"L'interface" graphique est de manière générale très sympa.

par contre il n'y a aucun moyen de sortir du jeu sans tuer son adversaire. 
Et en parcourant ton code, j'ai trouvé ce commentaire : `// IMPORTANT DE OUF !!!!!!!!!!!!!!!!!!!!A remettre en fin de dev prompt("Quel est le nom du joueur?");`  ligne 149.

De plus tu as surement vu pour plus tard mais les fonction weaponSelector entre autre ne sont pas utilisées.

PS : tu as utilisé les index, mais utiliser des if `data === 'name'` c'est comme faire un tableau associatif. Et pour ce genre d'utilisation, mon pote m'a conseillé [switch](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/switch) plutôt que if (même si je sais bien qu'on l'a pas encore vu)

**Comment by Arnocaster** [comment]
Hello,
Tu as bien trouvé : je n'ai pas fini, il me manquait deux trucs dans la gestion des tours j'ai séché. 
Je me suis mal organisé, j'ai passé trop de temps a faire des fonctions optionnelles avant d'avoir fini l'algorithme de base.
Mais j'ai trouvé en me reposant ce que je dois modifier :)
Pour sortir du jeux il faut taper "e" mais je ne l'ai pas indiqué dans l'interface (pas fini).

Weapon selector est utilisé ligne 197  et 239.

Je connais switch aussi ca a été un enfer de pas craquer XD 
Et oui j'ai fait deux fonctions de rapprochement du tableau pour rester dans ce que l'on a vu.
C'est une contrainte que je tenais a  garder pour m'obliger a bien bosser les bases.

Je te fait signe quand j'ai fini :)

**Comment by Arnocaster** [comment]
Thank you
